### ISSUE TITLE
Ext php in composer.json

### ISSUE THREAD

**Issue by FuriosoJack** [vinkla/hashids#137]
Please add 

```
 "ext-gmp": "*",
   "ext-bcmath": "*"
```

in the composer.json

**Comment by vinkla** [comment]
Since we don’t want to enforce one or the other we can’t add it to the `composer.json` file.

**Comment by equinoxmatt** [comment]
@vinkla - Essentially the dependencies are hidden, unless you see the composer suggestions. Packages should not be 'suggested' if they are literally required to operate.

**Comment by miquelfire** [comment]
I think the issue is that composer.json doesn't have a way to define either-or dependencies. So if you have bcmath, you don't need gmp. If you have gmp, you don't need bcmath.

I think at one point, the library did have a way to not require either of the two however, but because of the 32-bit builds of PHP limiting the size of the numbers usable for the end users, this was removed.

**Comment by vinkla** [comment]
As @miquelfire already has stated there is currently no way to define either-or dependencies. An error will be thrown if neither is available:
https://github.com/vinkla/hashids/blob/b61b918ff6307fbb4f5351987d096b5bfac39ee3/src/Hashids.php#L408
